### ISSUE TITLE
Typhoon Called Off

### ISSUE THREAD

**Issue by shidia** [nicupavel/openpanzer#47]
Just wanted to say that I am completely impressed with this game!  I am a huge fan of the entire Panzer General series and this game is just awesome!   I have run into only one issue in the 'Typhoon Called Off' scenario-  it says I have 5 objectives left to conquer but there are only 4 on the map.   I have tried multiple different ways of saving/ loading and even leaving and retaking objectives already conquered....  Any suggestions?

**Comment by Ronnieg1912** [comment]
Any fix to this yet as still stuck on this

**Comment by Tulipanes** [comment]
Nota that I know off

On Wed, Aug 26, 2015 at 5:11 PM Ronnieg1912 <notifications@github.com>
wrote:

> Any fix to this yet as still stuck on this
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nicupavel/openpanzer/issues/47#issuecomment-135157067>
> .
>
-- 
Alexandre de Mendonça Lima Tolipan
Alexandre Tolipan Advocacia
Av. Presidente Wilson 231, 5o andar
Centro - Rio de Janeiro -RJ
CEP. 20030-021
Brasil
http://www.tolipan.adv.br

O conteúdo desta mensagem é confidencial e pode constituir sigilo
profissional.
Caso não seja o destinatário da mesma, queira por gentileza nos informar
através do e-mail contato@tolipan.adv.br <contato@tbta.adv.br>.
Não é permitida a cópia ou divulgação desta mensagem a qualquer outra
pessoa.

This Email is confidential and may also be privileged.
If you are not the intended recipient please notify us by sending an e-mail
or contato@tolipan.adv.br.
You should not copy it or use it for any purpose nor disclose its contents
to any other person.

-- 
IMPORTANTE:

O conteúdo desta mensagem é confidencial e pode constituir sigilo 
profissional.
Caso não seja o destinatário da mesma, queira por gentileza nos informar 
através do e-mail contato@tbta.adv.br.
Não é permitida a cópia ou divulgação desta mensagem a qualquer outra 
pessoa.

This Email is confidential and may also be privileged.
If you are not the intended recipient please notify us by sending an e-mail 
or contato@tbta.adv.br.
You should not copy it or use it for any purpose nor disclose its contents 
to any other person.

**Comment by Ronnieg1912** [comment]
Thanks, thought as much.



Sent from my Sony Xperia™ smartphone

---- Tulipanes wrote ----

Nota that I know off

On Wed, Aug 26, 2015 at 5:11 PM Ronnieg1912 <notifications@github.com>
wrote:

> Any fix to this yet as still stuck on this
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nicupavel/openpanzer/issues/47#issuecomment-135157067>
> .
>
--
Alexandre de Mendonça Lima Tolipan
Alexandre Tolipan Advocacia
Av. Presidente Wilson 231, 5o andar
Centro - Rio de Janeiro -RJ
CEP. 20030-021
Brasil
http://www.tolipan.adv.br

O conteúdo desta mensagem é confidencial e pode constituir sigilo
profissional.
Caso não seja o destinatário da mesma, queira por gentileza nos informar
através do e-mail contato@tolipan.adv.br <contato@tbta.adv.br>.
Não é permitida a cópia ou divulgação desta mensagem a qualquer outra
pessoa.

This Email is confidential and may also be privileged.
If you are not the intended recipient please notify us by sending an e-mail
or contato@tolipan.adv.br.
You should not copy it or use it for any purpose nor disclose its contents
to any other person.

--
IMPORTANTE:

O conteúdo desta mensagem é confidencial e pode constituir sigilo
profissional.
Caso não seja o destinatário da mesma, queira por gentileza nos informar
através do e-mail contato@tbta.adv.br.
Não é permitida a cópia ou divulgação desta mensagem a qualquer outra
pessoa.

This Email is confidential and may also be privileged.
If you are not the intended recipient please notify us by sending an e-mail
or contato@tbta.adv.br.
You should not copy it or use it for any purpose nor disclose its contents
to any other person.


---

**Comment by Rjaap** [comment]
Sure you can. Save the game on the first turn of the scenario. Download the savegame. Open it in a json editor (there's a very good one online for free). Look for the map properties and find some suitable hex coordinates for deployment. Change the isdeployment property of the hex coordinate that you want to use for deployment from -1 to 0. Save the file and open it in the game. Now you have a fresh deployment hex :)

**Comment by RufusRedbeard** [comment]
Thanks very much for the tip Rjaap.  

The Panzers are rolling again :)

**Comment by Tulipanes** [comment]
After scenario hedgerows on campaign Das Reich I receive this message after
a brilliant victory.. what do I do?    "Couldn load map images"

On Thu, Sep 3, 2015 at 4:39 AM RufusRedbeard <notifications@github.com>
wrote:

> Thanks very much for the tip Rjaap.
>
> The Panzers are rolling again :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nicupavel/openpanzer/issues/47#issuecomment-137363035>
> .
>
-- 
Alexandre de Mendonça Lima Tolipan
Alexandre Tolipan Advocacia
Av. Presidente Wilson 231, 5o andar
Centro - Rio de Janeiro -RJ
CEP. 20030-021
Brasil
http://www.tolipan.adv.br

O conteúdo desta mensagem é confidencial e pode constituir sigilo
profissional.
Caso não seja o destinatário da mesma, queira por gentileza nos informar
através do e-mail contato@tolipan.adv.br <contato@tbta.adv.br>.
Não é permitida a cópia ou divulgação desta mensagem a qualquer outra
pessoa.

This Email is confidential and may also be privileged.
If you are not the intended recipient please notify us by sending an e-mail
or contato@tolipan.adv.br.
You should not copy it or use it for any purpose nor disclose its contents
to any other person.

-- 
IMPORTANTE:

O conteúdo desta mensagem é confidencial e pode constituir sigilo 
profissional.
Caso não seja o destinatário da mesma, queira por gentileza nos informar 
através do e-mail contato@tbta.adv.br.
Não é permitida a cópia ou divulgação desta mensagem a qualquer outra 
pessoa.

This Email is confidential and may also be privileged.
If you are not the intended recipient please notify us by sending an e-mail 
or contato@tbta.adv.br.
You should not copy it or use it for any purpose nor disclose its contents 
to any other person.

**Comment by nicupavel** [comment]
Fixed Typhoon Called Off extra objective

**Comment by nicupavel** [comment]
Fixed Operation Luttich

**Comment by nicupavel** [comment]
Fixed Operation Typhoon - Vyazma - added deployment hexes for Axis side

**Comment by Tulipanes** [comment]
sorry.. just accessed Typhoon - Vyazma and still have no deployment hexes.


On Thu, Oct 1, 2015 at 1:44 PM nicupavel <notifications@github.com> wrote:

> Fixed Operation Typhoon - Vyazma - added deployment hexes for Axis side
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nicupavel/openpanzer/issues/47#issuecomment-144783140>
> .
>
-- 
Alexandre de Mendonça Lima Tolipan
Alexandre Tolipan Advocacia
Av. Presidente Wilson 231, 5o andar
Centro - Rio de Janeiro -RJ
CEP. 20030-021
Brasil
http://www.tolipan.adv.br

O conteúdo desta mensagem é confidencial e pode constituir sigilo
profissional.
Caso não seja o destinatário da mesma, queira por gentileza nos informar
através do e-mail contato@tolipan.adv.br <contato@tbta.adv.br>.
Não é permitida a cópia ou divulgação desta mensagem a qualquer outra
pessoa.

This Email is confidential and may also be privileged.
If you are not the intended recipient please notify us by sending an e-mail
or contato@tolipan.adv.br.
You should not copy it or use it for any purpose nor disclose its contents
to any other person.

-- 
IMPORTANTE:

O conteúdo desta mensagem é confidencial e pode constituir sigilo 
profissional.
Caso não seja o destinatário da mesma, queira por gentileza nos informar 
através do e-mail contato@tbta.adv.br.
Não é permitida a cópia ou divulgação desta mensagem a qualquer outra 
pessoa.

This Email is confidential and may also be privileged.
If you are not the intended recipient please notify us by sending an e-mail 
or contato@tbta.adv.br.
You should not copy it or use it for any purpose nor disclose its contents 
to any other person.

**Comment by nicupavel** [comment]
Of course, it's fixed on my build, but I haven't made and updates to openpanzer.net/iOS/Android just yet.
I'm fixing current bugs and then I'll release.

**Comment by Tulipanes** [comment]
sorry not using the android version.. just the web version

On Thu, Oct 1, 2015 at 1:53 PM nicupavel <notifications@github.com> wrote:

> Of course, it's fixed on my build, but I haven't made and updates to
> openpanzer.net/iOS/Android just yet.
> I'm fixing current bugs and then I'll release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nicupavel/openpanzer/issues/47#issuecomment-144785260>
> .
>
-- 
Alexandre de Mendonça Lima Tolipan
Alexandre Tolipan Advocacia
Av. Presidente Wilson 231, 5o andar
Centro - Rio de Janeiro -RJ
CEP. 20030-021
Brasil
http://www.tolipan.adv.br

O conteúdo desta mensagem é confidencial e pode constituir sigilo
profissional.
Caso não seja o destinatário da mesma, queira por gentileza nos informar
através do e-mail contato@tolipan.adv.br <contato@tbta.adv.br>.
Não é permitida a cópia ou divulgação desta mensagem a qualquer outra
pessoa.

This Email is confidential and may also be privileged.
If you are not the intended recipient please notify us by sending an e-mail
or contato@tolipan.adv.br.
You should not copy it or use it for any purpose nor disclose its contents
to any other person.

-- 
IMPORTANTE:

O conteúdo desta mensagem é confidencial e pode constituir sigilo 
profissional.
Caso não seja o destinatário da mesma, queira por gentileza nos informar 
através do e-mail contato@tbta.adv.br.
Não é permitida a cópia ou divulgação desta mensagem a qualquer outra 
pessoa.

This Email is confidential and may also be privileged.
If you are not the intended recipient please notify us by sending an e-mail 
or contato@tbta.adv.br.
You should not copy it or use it for any purpose nor disclose its contents 
to any other person.

**Comment by Tulipanes** [comment]
Also tried Operation Luttich on openpanzer.net web and still not working

On Thu, Oct 1, 2015 at 1:55 PM Alexandre Tolipan <atolipan@tbta.adv.br>
wrote:

> sorry not using the android version.. just the web version
>
> On Thu, Oct 1, 2015 at 1:53 PM nicupavel <notifications@github.com> wrote:
>
>> Of course, it's fixed on my build, but I haven't made and updates to
>> openpanzer.net/iOS/Android just yet.
>> I'm fixing current bugs and then I'll release.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/nicupavel/openpanzer/issues/47#issuecomment-144785260>
>> .
>>
> --
> Alexandre de Mendonça Lima Tolipan
> Alexandre Tolipan Advocacia
> Av. Presidente Wilson 231, 5o andar
> Centro - Rio de Janeiro -RJ
> CEP. 20030-021
> Brasil
> http://www.tolipan.adv.br
>
> O conteúdo desta mensagem é confidencial e pode constituir sigilo
> profissional.
> Caso não seja o destinatário da mesma, queira por gentileza nos informar
> através do e-mail contato@tolipan.adv.br <contato@tbta.adv.br>.
> Não é permitida a cópia ou divulgação desta mensagem a qualquer outra
> pessoa.
>
> This Email is confidential and may also be privileged.
> If you are not the intended recipient please notify us by sending an
> e-mail or contato@tolipan.adv.br.
> You should not copy it or use it for any purpose nor disclose its contents
> to any other person.
>
-- 
Alexandre de Mendonça Lima Tolipan
Alexandre Tolipan Advocacia
Av. Presidente Wilson 231, 5o andar
Centro - Rio de Janeiro -RJ
CEP. 20030-021
Brasil
http://www.tolipan.adv.br

O conteúdo desta mensagem é confidencial e pode constituir sigilo
profissional.
Caso não seja o destinatário da mesma, queira por gentileza nos informar
através do e-mail contato@tolipan.adv.br <contato@tbta.adv.br>.
Não é permitida a cópia ou divulgação desta mensagem a qualquer outra
pessoa.

This Email is confidential and may also be privileged.
If you are not the intended recipient please notify us by sending an e-mail
or contato@tolipan.adv.br.
You should not copy it or use it for any purpose nor disclose its contents
to any other person.

-- 
IMPORTANTE:

O conteúdo desta mensagem é confidencial e pode constituir sigilo 
profissional.
Caso não seja o destinatário da mesma, queira por gentileza nos informar 
através do e-mail contato@tbta.adv.br.
Não é permitida a cópia ou divulgação desta mensagem a qualquer outra 
pessoa.

This Email is confidential and may also be privileged.
If you are not the intended recipient please notify us by sending an e-mail 
or contato@tbta.adv.br.
You should not copy it or use it for any purpose nor disclose its contents 
to any other person.

**Comment by nicupavel** [comment]
Fixes aren't out yet

**Comment by Tulipanes** [comment]
Ok.. thanks. Looking forward to it.

**Comment by escobarylvar0** [comment]
Dear nicupavel: I think Open General is a great game. The best I play. Aré there any news on the updates of the game?

**Comment by Tulipanes** [comment]
Dear Nicu,
 once again I restarted my addiction to open panzer. Nevertheless I found
an issue early on. I am playing the CLosing in on Dunkirk scenario of the
Das Reich campaing and realized that no matter that I takle the objectives
the game does not register it. So I now have taken them all adn cannot win
or finish the scenario.

On Thu, Oct 1, 2015 at 2:29 PM nicupavel <notifications@github.com> wrote:

> Fixes aren't out yet
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nicupavel/openpanzer/issues/47#issuecomment-144794159>
> .
>
-- 
Alexandre de Mendonça Lima Tolipan
Alexandre Tolipan Advocacia
Av. Presidente Wilson 231, 5o andar
Centro - Rio de Janeiro -RJ
CEP. 20030-021
Brasil
http://www.tolipan.adv.br

O conteúdo desta mensagem é confidencial e pode constituir sigilo
profissional.
Caso não seja o destinatário da mesma, queira por gentileza nos informar
através do e-mail contato@tolipan.adv.br <contato@tbta.adv.br>.
Não é permitida a cópia ou divulgação desta mensagem a qualquer outra
pessoa.

This Email is confidential and may also be privileged.
If you are not the intended recipient please notify us by sending an e-mail
or contato@tolipan.adv.br.
You should not copy it or use it for any purpose nor disclose its contents
to any other person.

-- 
IMPORTANTE:

O conteúdo desta mensagem é confidencial e pode constituir sigilo 
profissional.
Caso não seja o destinatário da mesma, queira por gentileza nos informar 
através do e-mail contato@tbta.adv.br.
Não é permitida a cópia ou divulgação desta mensagem a qualquer outra 
pessoa.

This Email is confidential and may also be privileged.
If you are not the intended recipient please notify us by sending an e-mail 
or contato@tbta.adv.br.
You should not copy it or use it for any purpose nor disclose its contents 
to any other person.
